name: Build and Test

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
  workflow_dispatch:
jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip 
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    #  - name: Run tests
    #    run: |
    #      python -m unittest discover

  semantic-release:
    runs-on: ubuntu-latest
    needs: build_and_test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install build and twine
        run: python -m pip install --upgrade pip build twine

      - name: Extract repository name
        run: |
          REPO_NAME=$(echo "${{ github.repository }}" | cut -d'/' -f2)
          echo "REPO_NAME=${REPO_NAME}" >> $GITHUB_ENV 

      - name: Semantic Release Custom Action
        uses: MitVo/semantic-release-action@python-smvers
        env:
          REPO_NAME: ${{ env.REPO_NAME }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          module_name: 'poc_module'
          pypi_token: ${{ secrets.PYPI_TOKEN }}
